steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cycling-coach/backend:$COMMIT_SHA'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cycling-coach/backend:latest'
      - '-f'
      - 'Dockerfile.backend'
      - '.'

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cycling-coach/backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cycling-coach/backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cycling-coach-backend'
      - '--image=asia-northeast3-docker.pkg.dev/$PROJECT_ID/cycling-coach/backend:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cycling-coach/backend:$COMMIT_SHA'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cycling-coach/backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
